version: '3.3'

services:
  # php - apache
  website:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php73
    restart: always
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html
    ports:
      - 8000:80
  #mysqli database
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./php/school:/docker-entrypoint-initdb.d
      - ./php/school/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
      MYSQL_USER: vasilis
      MYSQL_PASSWORD: vasilis
    ports:
      - 6033:3306
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
